In [1]:
import numpy as np


In [4]:

arr_zeros = np.zeros(10, dtype=int)


arr_zeros[4] = 1

print(arr_zeros)


[0 0 0 0 1 0 0 0 0 0]


In [5]:
arr_h = np.arange(10, 25)

print(arr_h[::-1])

[24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [10]:
arr_k = np.array([1, 2, 0, 8, 2, 0, 1, 3, 0, 5, 0])

arr_l = arr_k[arr_k != 0]

print(arr_l)

arr_1 = np.append(arr_l, [10, 20])
print(arr_1)

arr_1[5] = 100
print(arr_1)
print(arr_1[2:])

[1 2 8 2 1 3 5]
[ 1  2  8  2  1  3  5 10 20]
[  1   2   8   2   1 100   5  10  20]
[  8   2   1 100   5  10  20]
